"""
Vanguard Sentinel — Incident Report Route
GET /api/report/generate — Generates a markdown incident report from the current graph state.
"""

from fastapi import APIRouter, HTTPException
from backend.graph.neo4j_client import neo4j_client
from datetime import datetime

router = APIRouter()


@router.get("/api/report/generate")
async def generate_incident_report() -> dict:
    """Generate a markdown incident report from the current graph state.

    Queries the Neo4j knowledge graph for:
    - Entity statistics (node counts by label)
    - Active threat actor activity (attacks on assets)
    - Vulnerability assessments (CVEs linked to assets)
    - Containment actions (isolated assets)

    Returns:
        A dictionary containing the markdown report, generation timestamp,
        and raw graph statistics.
    """
    try:
        # ─── Query graph statistics ──────────────────────────
        stats: list[dict] = neo4j_client.run_cypher("""
            MATCH (n)
            WITH labels(n)[0] AS label, count(*) AS count
            RETURN label, count ORDER BY count DESC
        """)

        # ─── Query critical threats ──────────────────────────
        threats: list[dict] = neo4j_client.run_cypher("""
            MATCH (ta:ThreatActor)-[r]->(a:Asset)
            RETURN ta.name AS actor, type(r) AS action, a.hostname AS target
            LIMIT 20
        """)

        # ─── Query vulnerabilities ───────────────────────────
        vulns: list[dict] = neo4j_client.run_cypher("""
            MATCH (v:Vulnerability)-[r]->(a:Asset)
            RETURN v.cve_id AS cve, v.severity AS severity, a.hostname AS affected_asset
            LIMIT 20
        """)

        # ─── Query isolated assets ───────────────────────────
        isolated: list[dict] = neo4j_client.run_cypher("""
            MATCH (a:Asset {isolated: true})
            RETURN a.hostname AS hostname
        """)

        # ─── Build markdown report ───────────────────────────
        now: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_id: str = f"RPT-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        report: str = f"""# 🛡️ Vanguard Sentinel — Incident Report

**Generated:** {now}
**Classification:** CONFIDENTIAL
**Report ID:** {report_id}

---

## Executive Summary

This automated incident report was generated by the Vanguard Sentinel threat
intelligence platform. It provides a point-in-time snapshot of the current
knowledge graph state, including entity statistics, active threat actor
activity, vulnerability assessments, and containment actions.

## Graph Statistics

| Entity Type | Count |
|-------------|-------|
"""

        for s in stats:
            report += f"| {s['label']} | {s['count']} |\n"

        # ─── Threat actors section ───────────────────────────
        report += "\n## Active Threat Actors\n\n"
        if threats:
            report += "| Threat Actor | Action | Target Asset |\n"
            report += "|--------------|--------|--------------|\n"
            for t in threats:
                report += f"| {t['actor']} | {t['action']} | {t['target']} |\n"
        else:
            report += "No active threat actor activity detected.\n"

        # ─── Vulnerabilities section ─────────────────────────
        report += "\n## Vulnerability Assessment\n\n"
        if vulns:
            report += "| CVE ID | Severity | Affected Asset |\n"
            report += "|--------|----------|----------------|\n"
            for v in vulns:
                severity = v.get("severity", "N/A") or "N/A"
                report += f"| {v['cve']} | {severity} | {v['affected_asset']} |\n"
        else:
            report += "No vulnerabilities currently linked to assets.\n"

        # ─── Containment section ─────────────────────────────
        report += "\n## Containment Actions\n\n"
        if isolated:
            report += "The following assets have been isolated:\n\n"
            for i in isolated:
                report += f"- 🔒 `{i['hostname']}`\n"
        else:
            report += "No assets currently isolated.\n"

        # ─── Footer ─────────────────────────────────────────
        report += "\n---\n\n*Report generated by Vanguard Sentinel v0.1.0*\n"

        return {
            "report": report,
            "generated_at": now,
            "report_id": report_id,
            "stats": stats,
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Report generation failed: {str(e)}",
        )
